import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/contexts/Providers'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Tech Nova',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}