import { Inter } from 'next/font/google'
import '../globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex'>
          <div className="h-screen w-28 bg-primary">Hola</div>
          {children}
        </div>
      </body>
    </html>
  )
}
