import { NavBar } from '@/Components/Molecules/NavBar/NavBar'

export const metadata = {
  title: 'Tech Nova',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
        <NavBar></NavBar>
        {children}
    </>
  )
}
